version: '3'

vars:
  NAMESPACE: my-smia

includes:
  ext:
    taskfile: ./external
    dir: ./external
  app:
    taskfile: ./app
    dir: ./app

tasks:
  all:
    desc: すべてをデプロイします
    cmds:
      - task: ext:all
      - task: app:all
  setup:
    internal: true
    run: once
    deps:
      - task: namespace
  use-context:
    internal: true
    run: once
    cmds:
      - |-
        {{if eq .ENV "aws"}}
        aws eks update-kubeconfig --name ostock-dev-cluster --alias ostock-dev-cluster
        {{else}}
        kubectl config use-context docker-desktop
        {{end}}
      - kubectl config set-context --current --namespace={{.NAMESPACE}}
  namespace:
    desc: 名前空間を作成します
    deps:
      - task: use-context
    cmds:
      - kubectl create namespace {{.NAMESPACE}}
    status:
      - kubectl get namespace {{.NAMESPACE}}
  destroy:
    desc: 全てを無かったことにします
    deps:
      - task: setup
    cmds:
      - task: ext:helm-destroy
      - kubectl -n {{.NAMESPACE}} delete all --all
