spring:
  cloud.loadbalancer.ribbon.enabled: false
  zipkin.baseUrl: http://zipkin:9411

# Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true

eureka.client.serviceUrl.defaultZone: http://eureka-server:8070/eureka/

logstash.host: logstash:5000

security:
  oauth2:
    resource:
      userInfoUri: http://authentication-service:8082/user
    client:
      grant-type: client_credentials
