spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://database:5432/ostock_dev?sslmode=disable
    testWhileIdle: true
    validationQuery: SELECT 1
    username: postgres
  database:
    driverClassName: org.postgresql.Driver
