spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin

eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
