version: '3'

env:
  DOCKER_HOST:
    sh: docker context inspect | jq -r '.[0].Endpoints.docker.Host'

tasks:
  build-images:
    desc: 全てのアプリケーションイメージをビルドします
    cmds:
      - mvn clean package dockerfile:build
  build-image:
    desc: 指定されたアプリケーションイメージをビルドします
    dir: './{{.CLI_ARGS}}'
    cmds:
      - mvn clean package dockerfile:build
